title: "Avisos 5S2M-B"
baseurl: "/avisos5S2M-B" 
url: "https://ggelado.github.io"
theme: jekyll-theme-primer
locale: es_ES.UTF-8
lang: es-ES
plugins:
  - jekyll-feed # plugin para generar RSS autom√°ticamente
feed:
  posts_limit: 100



